site_name: Index.py
site_description: 一个基于 ASGI 协议的异步 Web 框架.

theme:
    name: 'material'
    language: 'zh'

repo_name: abersheeran/index.py
repo_url: https://github.com/abersheeran/index.py
edit_uri: ""

nav:
  - Get Start: 'index.md'
  - Configuration: 'config.md'
  - HTTP: 'http.md'
  - WebSocket: 'websocket.md'
  - Mount: 'mount.md'
  - Lifespan: 'event.md'
  - Command: 'command.md'
  - OpenAPI ᴮᴱᵀᴬ: 'openapi.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
