site_name: Index.py
site_description: 一个基于 ASGI 协议的异步 Web 框架.

theme:
  name: 'material'
  language: 'zh'
  feature:
    tabs: true

repo_name: index.py
repo_url: https://github.com/abersheeran/index.py
edit_uri: "https://github.com/abersheeran/index.py/tree/master/docs/"

nav:
  - 介绍: "index.md"
  - 简单使用:
    - 第一步: 'firststep/index.md'
  - 配置:
    - 配置介绍: 'config/index.md'
    - 配置列表: 'config/list.md'
  - HTTP:
    - HTTP: 'http/http.md'
    - Response: 'http/response.md'
    - Middleware: 'http/middleware.md'
    - OpenAPI: 'http/openapi.md'
    - Exception: 'http/exception.md'
    - Background: 'http/background.md'
  - WebSocket:
    - 'websocket.md'
  - Lifespan:
    - 'event.md'
  - Mount:
    - 'mount.md'
  - Test:
    - 'test.md'
  - Command:
    - 'command.md'
  - 额外知识:
    - 热重载的注意事项: 'knowledge/hotreload.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
