site_name: Index.py
site_description: 一个基于 ASGI 协议的异步 Web 框架.

theme:
    name: 'material'

repo_name: abersheeran/index.py
repo_url: https://github.com/abersheeran/index.py
edit_uri: ""

nav:
  - 开始: 'index.md'
  - 配置: 'config.md'
  - HTTP:
    - 请求: 'http.md'
    - 响应: 'response.md'
    - 中间件: 'middleware.md'
  - Websocket:
    - 处理: 'websocket.md'
  - 挂载其他应用: 'mount.md'
  - 事件: 'event.md'
  - 命令: 'command.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
