site_name: Index.py
site_description: 一个基于 ASGI 协议的异步 Web 框架.

theme:
    name: 'material'

repo_name: abersheeran/index.py
repo_url: https://github.com/abersheeran/index.py
edit_uri: ""

nav:
    - 最初的开始: 'index.md'
    - 可用的配置: 'config.md'
    - 处理 HTTP: 'view.md'
    - HTTP 响应对象: 'response.md'
    - 处理 Websocket: 'websocket.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
