name: Deploy GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'mkdocs.yml'
      - 'docs/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip mkdocs mkdocs-material mkdocs-version

      - name: Build
        run: |
          mkdocs-version build --minor --min-version=v0.10.0 --version-regex="v(?P<version>.*)"
          echo index-py.abersheeran.com > site/CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
